version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
        restart: unless-stopped
        depends_on:
            - app
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '10'
        container_name: nginx_docker_diploma
        networks:
            - diploma

    app: # docker-compose exec app php artisan ..
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '10'
        container_name: app_docker_diploma
        image: diploma
        networks:
            - diploma


    db: # docker-compose exec db bash =>  mysql -u root -p => show databases;
        image: mysql:5.7
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '10'
        container_name: db_docker_diploma
        networks:
            - diploma

    websockets:
        image: diploma
        command: [ 'php', 'artisan', 'websockets:serve' ]
        container_name: websockets_docker_diploma
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - '6001:6001'
        networks:
            - diploma

    #docker run -d -v /elasticsearch/data:/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 --name elasticsearch_docker_diploma elasticsearch:2.4.1 -Des.cluster.name="elasticsearch_docker_diploma"
    elasticsearch:
        container_name: elasticsearch_docker_diploma
        image: library/elasticsearch:8.0.1 #TODO нужно следить за версиями, если слишком старая версия, то не будут работать ноды в elastic
        environment:
            - Des.cluster.name=diplomas-data-cluster
            - xpack.security.enabled=false
            - "discovery.type=single-node"
        volumes:
            - diplomas-data:/usr/share/elasticsearch/data
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            - diploma

networks:
    diploma:
        driver: bridge

volumes:
    diplomas-data:
        driver: local
