version: '3'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8080:80"
        depends_on:
            - app
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '10'
        container_name: nginx_docker_diploma

    app: # docker-compose exec app php artisan ..
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '10'
        container_name: app_docker_diploma


    db: # docker-compose exec db bash =>  mysql -u root -p => show databases;
        image: mysql:5.7
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '10'
        container_name: db_docker_diploma
